backend:
  name: git-gateway
  branch: master

media_folder: "public/cms"

collections:
  - name: "game" # Used in routes, e.g., /admin/collections/blog
    label: "Game Post" # Used in the UI
    folder: "public/cms/games" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "game-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "card"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Game Link", name: "link", widget: "string"}
      - {label: "Game Code", name: "code", widget: "string"}
        
  - name: "website" # Used in routes, e.g., /admin/collections/blog
    label: "Website" # Used in the UI
    folder: "public/cms/sites" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "site-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "card"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Site Link", name: "link", widget: "string"}